spring.application.name=api-treinos
spring.datasource.url=jdbc:postgresql://localhost:5432/api_treinos_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
api.security.token.secret=${JWT_SECRET}