spring.datasource.url=jdbc:postgresql://localhost:5432/api_treinos_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.level.com.portfolio.api_treinos=DEBUG
logging.level.org.springframework.security=DEBUG